"""empty message

Revision ID: 52ba28d9828d
Revises: 085355057a8c
Create Date: 2022-03-22 21:06:35.143915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52ba28d9828d'
down_revision = '085355057a8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('price', sa.Float(), nullable=True))
    op.create_index(op.f('ix_cars_price'), 'cars', ['price'], unique=False)
    op.add_column('rentals', sa.Column('total_price', sa.Float(), nullable=True))
    op.create_index(op.f('ix_rentals_total_price'), 'rentals', ['total_price'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rentals_total_price'), table_name='rentals')
    op.drop_column('rentals', 'total_price')
    op.drop_index(op.f('ix_cars_price'), table_name='cars')
    op.drop_column('cars', 'price')
    # ### end Alembic commands ###
