"""empty message

Revision ID: aca55f82ffdb
Revises: 7df367f7784b
Create Date: 2022-04-26 19:40:16.230289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aca55f82ffdb'
down_revision = '7df367f7784b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rentals', sa.Column('paid', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_rentals_paid'), 'rentals', ['paid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rentals_paid'), table_name='rentals')
    op.drop_column('rentals', 'paid')
    # ### end Alembic commands ###
