"""empty message

Revision ID: acfffcabed23
Revises: 0d9b40c40dc8
Create Date: 2022-05-24 14:54:03.092073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acfffcabed23'
down_revision = '0d9b40c40dc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rentals', sa.Column('returned', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_rentals_returned'), 'rentals', ['returned'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rentals_returned'), table_name='rentals')
    op.drop_column('rentals', 'returned')
    # ### end Alembic commands ###
